export const C2S = {
  JOIN: 'player:join',
  REBUY: 'player:rebuy',
  SIT_OUT: 'player:sit_out',
  SIT_IN: 'player:sit_in',
  ACTION: 'player:action',
  RIT_RESPONSE: 'player:rit_response',
  SHOW_CARDS: 'player:show_cards',
  GET_HISTORY: 'player:get_history',
  GET_HAND: 'player:get_hand',
  RECONNECT: 'player:reconnect',
  REPORT_BUG: 'player:report_bug',
  SIT_OUT_NEXT_HAND: 'player:sit_out_next_hand',
  AUTO_MUCK: 'player:auto_muck',
  CHAT: 'player:chat',
  UPDATE_AVATAR: 'player:update_avatar',
  CHIP_TRICK: 'player:chip_trick',
  CHANGE_SEAT: 'player:change_seat',
} as const;

export const S2C_PLAYER = {
  CONNECTED: 'player:connected',
  ERROR: 'player:error',
  LOBBY_STATE: 'player:lobby_state',
  PRIVATE_STATE: 'player:private_state',
  HAND_START: 'player:hand_start',
  YOUR_TURN: 'player:your_turn',
  RIT_OFFER: 'player:rit_offer',
  RIT_RESOLVED: 'player:rit_resolved',
  SHOW_CARDS_OFFER: 'player:show_cards_offer',
  HAND_RESULT: 'player:hand_result',
  BUSTED: 'player:busted',
  REBUY_PROMPT: 'player:rebuy_prompt',
  HISTORY_LIST: 'player:history_list',
  HAND_DETAIL: 'player:hand_detail',
  SOUND: 'player:sound',
  JOINED: 'player:joined',
  BUG_REPORTED: 'player:bug_reported',
  RECONNECTED: 'player:reconnected',
  RECONNECT_FAILED: 'player:reconnect_failed',
  CHAT_MESSAGE: 'player:chat_message',
} as const;

export const C2S_LOBBY = {
  GET_TABLES: 'lobby:get_tables',
  CREATE_TABLE: 'lobby:create_table',
  JOIN_TABLE: 'lobby:join_table',
  LEAVE_TABLE: 'lobby:leave_table',
  CHECK_NAME: 'lobby:check_name',
  REGISTER: 'lobby:register',
  LOGIN: 'lobby:login',
  DEPOSIT: 'lobby:deposit',
  SESSION_AUTH: 'lobby:session_auth',
} as const;

export const S2C_LOBBY = {
  TABLE_LIST: 'lobby:table_list',
  TABLE_CREATED: 'lobby:table_created',
  TABLE_UPDATED: 'lobby:table_updated',
  TABLE_REMOVED: 'lobby:table_removed',
  ERROR: 'lobby:error',
  NAME_STATUS: 'lobby:name_status',
  AUTH_SUCCESS: 'lobby:auth_success',
  AUTH_ERROR: 'lobby:auth_error',
  BALANCE_UPDATE: 'lobby:balance_update',
} as const;

export const C2S_TABLE = {
  GET_HISTORY: 'table:get_history',
  GET_HAND: 'table:get_hand',
  WATCH: 'table:watch',
  UNWATCH: 'table:unwatch',
} as const;

export const S2C_TABLE = {
  GAME_STATE: 'table:game_state',
  PLAYER_JOINED: 'table:player_joined',
  PLAYER_LEFT: 'table:player_left',
  HAND_START: 'table:hand_start',
  CARDS_DEALT: 'table:cards_dealt',
  PLAYER_ACTION: 'table:player_action',
  STREET_DEAL: 'table:street_deal',
  POT_UPDATE: 'table:pot_update',
  SHOWDOWN: 'table:showdown',
  HAND_RESULT: 'table:hand_result',
  POT_AWARD: 'table:pot_award',
  PLAYER_TIMER: 'table:player_timer',
  RIT_ACTIVE: 'table:rit_active',
  SECOND_BOARD_DEALT: 'table:second_board_dealt',
  HISTORY_LIST: 'table:history_list',
  HAND_DETAIL: 'table:hand_detail',
  SOUND: 'table:sound',
  ALLIN_SHOWDOWN: 'table:allin_showdown',
  EQUITY_UPDATE: 'table:equity_update',
  CHAT_MESSAGE: 'table:chat_message',
  BAD_BEAT: 'table:bad_beat',
  CHIP_TRICK: 'table:chip_trick',
} as const;
