export const basicSlogans: string[] = [
  'Lucky river...',
  "That's poker I guess",
  'Runner runner, really?',
  'Are you kidding me?!',
  'One outer? Seriously?',
  'I had that locked up!',
  'The poker gods hate me',
  'Unbelievable...',
  'How do you call that?!',
  'Rivered. Again.',
  "Can't believe that hit",
  'Nice catch...',
  'What a joke',
  'Story of my life',
  'I quit. Not really.',
  'Must be nice',
  "That's not even legal",
  'Wow. Just wow.',
  'Cool cool cool...',
  'Thanks dealer',
  'Rigged!',
  'Of course it got there',
  'Why do I play this game',
  'Brutal.',
  'Two-outer and you find it',
  "Can't win 'em all I guess",
  'Classic.',
  'GG I suppose',
  'Nice hand... I guess',
  "Well that's unfortunate",
  'I was 95%!',
  'What were the odds?!',
  "Dealer, you're fired",
  'Goodbye cruel river',
  'I need a drink',
  'That was disgusting',
  "I can't even",
  'Perfect. Just perfect.',
  'Someone call the police',
  'Robbery!',
  'This game is broken',
  'Sure, give them the miracle card',
  'Read it and weep... oh wait',
  'Sigh.',
  'I was so far ahead...',
  'The math is broken',
  'Statistical impossibility',
  'That card was MY card',
  'Pain.',
  'Tell me this is a simulation',
  'Is this real life?',
  'Absolutely criminal',
  'You owe me one, universe',
  'Fading everything except THAT?!',
  'That card had my name on it',
  'Variance is just variance, right?',
  "I'm running so bad",
  'This is fine. Everything is fine.',
  'Just a cooler bro',
  'How much equity did I have? A LOT.',
  'This is why people go broke',
  'Fade everything... except that',
  "I didn't sign up for this",
  'Next hand. NEXT. HAND.',
  'My therapist will hear about this',
  'The river giveth and the river taketh',
  'Outplayed... by the deck',
  'They needed exactly that card',
  'One time? Not this time.',
  'Thanks for the lesson, RNG',
  'Poker is a game of skill, they said',
  'Good game... no wait, bad game',
  'Soul read, soul crushed',
  "I'm never lucky",
  'Did that just happen?',
  'Fade the river they said...',
  'That hurt. That really hurt.',
  'LOL ok then',
  'Sick.',
  "Didn't need that money anyway",
  'I was drawing dead to a bad beat',
  'Even the dealer felt that one',
  'The worst card in the deck',
  'So you had two outs? Cool.',
  'Speechless.',
  'I was fist-pumping too early',
  'The deck has spoken',
  'Never had a chance... to win apparently',
  'Well THAT just happened',
  'Insert sad trombone here',
  'Somewhere a stats professor is crying',
  'Not like this...',
  'Back to the drawing board',
  "I'll remember that one",
  'Zero justice in this world',
  'Punished for playing well',
  'This is literally impossible',
  'The universe said no',
  'That was my tournament life!',
  'Bad beat? BAD BEAT.',
];
