export const cccpSlogans: string[] = [
  'The revolution will not be folded!',
  'Comrade, the river belongs to the people!',
  'In Soviet Russia, river catches YOU!',
  'Workers of the world, I was ahead!',
  'This is capitalist propaganda!',
  'The proletariat demands a redeal!',
  'For the Motherland, I call!',
  'Lenin would never allow this!',
  'The five-year plan did not include this river!',
  'Redistribution of chips is NOT poker!',
  'Comrade Dealer is a counter-revolutionary!',
  'The Party will hear about this!',
  'Glory to the working class! Not the river class!',
  'This is not how we do things in the Soviet Union!',
  'My equity was collectivized!',
  'The Politburo will review this hand!',
  'From each according to his equity, apparently!',
  'The Iron Curtain could not stop that river!',
  'Sputnik had better odds!',
  'This is why we have five-year plans!',
  'Comrade, that was MY pot!',
  'The revolution has been postponed!',
  'Red Square has seen less drama!',
  'That river was anti-Soviet!',
  'The people demand justice!',
  'This is a crime against the state!',
  'Even Brezhnev would fold here!',
  'My cards served the motherland faithfully!',
  'The KGB will investigate this dealer!',
  'Pravda would not print this hand!',
  'The dialectic says I should have won!',
  'Historical materialism was on my side!',
  'The means of production have been seized... from me!',
  'Solidarity with all bad beat victims!',
  'The class struggle continues at the poker table!',
  'My hand was pure communist ideology — and it lost!',
  'That river card was a bourgeois conspiracy!',
  'We will rebuild! The Soviet way!',
  'Comrade, I demand a people\'s tribunal!',
  'The tractor factory runs smoother than this game!',
  'Our glorious hand has fallen!',
  'The winter is cold, but this beat is colder!',
  'Even in Siberia, the odds are better!',
  'The collective farm of equity has been plundered!',
  'A great leap... backward!',
  'The party line says I was favorite!',
  'This river is revisionist history!',
  'Cosmonauts in orbit felt that beat!',
  'The eternal flame burns for my equity!',
  'The Bolshevik revolution started with less injustice!',
  'Comrade River has betrayed the revolution!',
  'The Iron Curtain of equity has been breached!',
  'This is not what Marx envisioned!',
  'The Soviet calculator says I was 95%!',
  'Glory to the aces! Wait... no glory.',
  'The Red Army could not defend this lead!',
  'Perestroika of the pot!',
  'Glasnost reveals: I was robbed!',
  'The gulag awaits that river card!',
  'My hand was a hero of the Soviet Union!',
  'The motherland weeps!',
  'This beat echoes through the Kremlin!',
  'The hammer struck my equity!',
  'The sickle cut my lead!',
  'Together we are strong! Except at this table!',
  'The workers\' paradise does not include this seat!',
  'Central planning failed this hand!',
  'The cosmonaut of poker has crash-landed!',
  'Soviet engineering could not prevent this!',
  'That river was a capitalist infiltration!',
  'The red flag flies at half-mast!',
  'My hand report has been filed with the Party!',
  'The proletariat will rise again! Next hand!',
  'Trotsky was exiled for less than this!',
  'The KGB has opened a file on this river!',
  'Comrade Luck has defected!',
  'The Siberian Express just hit my stack!',
  'Our five-year equity plan has failed!',
  'The socialist dream dies on the river!',
  'Even the Volga does not flow this cruelly!',
  'The Red October of bad beats!',
  'Comrade, pass the vodka',
  'The collective has voted: this is unjust!',
  'Soviet mathematics does not support this outcome!',
  'The revolution will resume next hand!',
  'My equity has been sent to the gulag!',
  'The Politburo has condemned this river!',
  'Stalingrad was an easier battle!',
  'The hammer and sickle weep for my chips!',
  'The people\'s court finds the river guilty!',
  'This hand is being reported to Moscow!',
  'The eternal flame of equity has been extinguished!',
  'A counter-revolutionary river if I ever saw one!',
  'The party platform did NOT include this beat!',
  'Comrade Cards, you have betrayed us all!',
  'The tundra is warmer than this table!',
  'The Soviet anthem plays for my fallen chips!',
  'Not even the Iron Curtain could block that out!',
  'The bear has been poked and the bear is angry!',
  'Victory was ours... until it wasn\'t!',
];
