default_platform(:ios)

platform :ios do
  desc "Push a new build to TestFlight"
  lane :beta do
    increment_build_number
    build_app(
      scheme: "PokerSofta",
      export_method: "app-store"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Run tests"
  lane :test do
    run_tests(
      scheme: "PokerSofta",
      device: "iPhone 16"
    )
  end
end
